### ISSUE TITLE
如何在拦截器里面增加公共的请求参数?

### ISSUE THREAD

**Issue by ZcChang** [AbnerMing888/HarmonyOsNet#18]
我在拦截器中的 prepareRequest 方法内增加了  request.setParams（）的方法，原本以为会在请求中增加参数，结果是覆盖了，这个应该怎么弄一下？小白 纯新人

**Comment by AbnerMing888** [comment]
这个需要增加一个属性，下个版本我添加一下

**Comment by ZcChang** [comment]
好的 多谢大佬

**Comment by ZcChang** [comment]
> 这个需要增加一个属性，下个版本我添加一下

最近两个版本 没发现您说添加的属性啊
