### ISSUE TITLE
请求失败

### ISSUE THREAD

**Issue by KnightAndroid** [AbnerMing888/HarmonyOsNet#8]
DevEco Studio NEXT Developer Preview2

HarmonyOS next Developer Preview2

这个版本下请求失败，麻烦看看

**Comment by AbnerMing888** [comment]
这个库已经投入正式项目了，目前没发现失败的问题，方便能告诉下如何请求的吗

**Comment by KnightAndroid** [comment]
> 这个库已经投入正式项目了，目前没发现失败的问题，方便能告诉下如何请求的吗

不过意思，是我调用问题，请把这个issue关闭，谢谢
