### ISSUE TITLE
快捷设置入参Params例子有么？

### ISSUE THREAD

**Issue by kevin161** [AbnerMing888/HarmonyOsNet#9]
我在使用setParams(),提示需要创建一个显示声明的类对象。感觉不是很方便。有便捷的设置入参的方法么？

**Comment by kevin161** [comment]
可不可以传入Map类型的数据，这样在拦截器中追加参数也会方便操作些？

**Comment by kevin161** [comment]
用了Record解决了，这跟Map也没什么区别啊，不知道为什么新搞个Record类

**Comment by kevin161** [comment]
用了Record解决了，这跟Map也没什么区别啊，不知道为什么新搞个Record类

**Comment by AbnerMing888** [comment]
参数支持很多类型：string | Object | ArrayBuffer | Record<string, Object>
